# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1047, 463)
        self.Taccuracy = QtWidgets.QLabel(Form)
        self.Taccuracy.setGeometry(QtCore.QRect(390, 170, 631, 51))
        self.Taccuracy.setObjectName("Taccuracy")
        self.Taccuracy_3 = QtWidgets.QLabel(Form)
        self.Taccuracy_3.setGeometry(QtCore.QRect(390, 270, 631, 51))
        self.Taccuracy_3.setObjectName("Taccuracy_3")
        self.exit = QtWidgets.QPushButton(Form)
        self.exit.setGeometry(QtCore.QRect(890, 360, 121, 41))
        self.exit.setObjectName("exit")
        self.training = QtWidgets.QPushButton(Form)
        self.training.setGeometry(QtCore.QRect(750, 360, 121, 41))
        self.training.setObjectName("training")
        self.dataset = QtWidgets.QPushButton(Form)
        self.dataset.setGeometry(QtCore.QRect(40, 90, 121, 41))
        self.dataset.setObjectName("dataset")
        self.training_rate = QtWidgets.QLineEdit(Form)
        self.training_rate.setGeometry(QtCore.QRect(220, 270, 113, 31))
        self.training_rate.setObjectName("training_rate")
        self.training_rate_label = QtWidgets.QLabel(Form)
        self.training_rate_label.setGeometry(QtCore.QRect(50, 260, 151, 51))
        self.training_rate_label.setObjectName("training_rate_label")
        self.Taccuracy_2 = QtWidgets.QLabel(Form)
        self.Taccuracy_2.setGeometry(QtCore.QRect(390, 220, 641, 51))
        self.Taccuracy_2.setObjectName("Taccuracy_2")
        self.epoch_label = QtWidgets.QLabel(Form)
        self.epoch_label.setGeometry(QtCore.QRect(50, 180, 111, 41))
        self.epoch_label.setObjectName("epoch_label")
        self.epoch = QtWidgets.QLineEdit(Form)
        self.epoch.setGeometry(QtCore.QRect(180, 180, 113, 31))
        self.epoch.setObjectName("epoch")
        self.data_name = QtWidgets.QLabel(Form)
        self.data_name.setGeometry(QtCore.QRect(200, 80, 791, 51))
        self.data_name.setObjectName("data_name")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Taccuracy.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">training accuracy:</span></p></body></html>"))
        self.Taccuracy_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">weight:</span></p></body></html>"))
        self.exit.setText(_translate("Form", "Exit"))
        self.training.setText(_translate("Form", "Training"))
        self.dataset.setText(_translate("Form", "Dataset"))
        self.training_rate_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">training_rate</span></p></body></html>"))
        self.Taccuracy_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">test accuracy:</span></p></body></html>"))
        self.epoch_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">epoch</span></p></body></html>"))
        self.data_name.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">...</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
