# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1060, 824)
        self.dataset = QtWidgets.QPushButton(Form)
        self.dataset.setGeometry(QtCore.QRect(40, 620, 121, 41))
        self.dataset.setObjectName("dataset")
        self.data_name = QtWidgets.QLabel(Form)
        self.data_name.setGeometry(QtCore.QRect(200, 610, 671, 51))
        self.data_name.setObjectName("data_name")
        self.Test_data = QtWidgets.QTextEdit(Form)
        self.Test_data.setGeometry(QtCore.QRect(70, 70, 421, 471))
        self.Test_data.setObjectName("Test_data")
        self.recall = QtWidgets.QTextEdit(Form)
        self.recall.setGeometry(QtCore.QRect(570, 70, 421, 471))
        self.recall.setObjectName("recall")
        self.test_data_lable = QtWidgets.QLabel(Form)
        self.test_data_lable.setGeometry(QtCore.QRect(220, 20, 121, 51))
        self.test_data_lable.setObjectName("test_data_lable")
        self.recall_label = QtWidgets.QLabel(Form)
        self.recall_label.setGeometry(QtCore.QRect(700, 30, 151, 41))
        self.recall_label.setObjectName("recall_label")
        self.train = QtWidgets.QPushButton(Form)
        self.train.setGeometry(QtCore.QRect(190, 690, 111, 51))
        self.train.setObjectName("train")
        self.how_many_pic_label = QtWidgets.QLabel(Form)
        self.how_many_pic_label.setGeometry(QtCore.QRect(40, 570, 591, 41))
        self.how_many_pic_label.setObjectName("how_many_pic_label")
        self.which_data = QtWidgets.QLineEdit(Form)
        self.which_data.setGeometry(QtCore.QRect(40, 776, 113, 31))
        self.which_data.setObjectName("which_data")
        self.show_butt = QtWidgets.QPushButton(Form)
        self.show_butt.setGeometry(QtCore.QRect(190, 766, 121, 41))
        self.show_butt.setObjectName("show_butt")
        self.data_not_exist = QtWidgets.QLabel(Form)
        self.data_not_exist.setGeometry(QtCore.QRect(350, 770, 281, 31))
        self.data_not_exist.setObjectName("data_not_exist")
        self.epoch = QtWidgets.QLineEdit(Form)
        self.epoch.setGeometry(QtCore.QRect(40, 700, 113, 31))
        self.epoch.setObjectName("epoch")
        self.data_not_exist_2 = QtWidgets.QLabel(Form)
        self.data_not_exist_2.setGeometry(QtCore.QRect(350, 700, 131, 31))
        self.data_not_exist_2.setObjectName("data_not_exist_2")
        self.noise = QtWidgets.QDoubleSpinBox(Form)
        self.noise.setGeometry(QtCore.QRect(490, 690, 111, 41))
        self.noise.setMaximum(1.0)
        self.noise.setSingleStep(0.01)
        self.noise.setObjectName("noise")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.dataset.setText(_translate("Form", "Dataset"))
        self.data_name.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">...</span></p></body></html>"))
        self.test_data_lable.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">Test Data</span></p></body></html>"))
        self.recall_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">Recall result</span></p></body></html>"))
        self.train.setText(_translate("Form", "Train"))
        self.how_many_pic_label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">There is no dataset be chossen.</span></p></body></html>"))
        self.show_butt.setText(_translate("Form", "show"))
        self.data_not_exist.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">The picture is not exist.<br/></span></p></body></html>"))
        self.data_not_exist_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:18pt;\">Noise Rate</span></p></body></html>"))
